### ISSUE TITLE
[Zoomable] Double-Tap zoom point

### ISSUE THREAD

**Issue by ajans** [Mr-Pine/AndroidUtilityLibraries#3]
Hi,

I would propose a little behavior optimization in that the `Zoomable` should zoom in on the last touchpoint when using the double-tap zoom feature (which is awesome, by the way).

Would that be possible to implement?

**Comment by Mr-Pine** [comment]
Good Idea! I'll look into it...

**Comment by Mr-Pine** [comment]
This is now the default behaviour in v1.1.0

**Comment by ajans** [comment]
Thank you! I will test it and let you know how it works for me.

**Comment by ajans** [comment]
Works great!
