### ISSUE TITLE
[Zoomable] Add boolean-parameter to turn off rotation

### ISSUE THREAD

**Issue by ajans** [Mr-Pine/AndroidUtilityLibraries#4]
Hi,

thank you for awesome library! I found nothing else as sophisticated as your Zoomables, great job!

As I am in the process of implementing an image-gallery, I would like to disable content-rotation.

So it would be nice to have a booelan-flag to enable/disable rotation for the `Zoomable`-composable-function.
The boolean-parameter `lockRotationOnZoomPan` would then only take effect if rotation is enabled.

Would you be open to implement such a feature or alternatively for a Merge Request for me to add this?

**Comment by Mr-Pine** [comment]
This would be handled by `ZoomableState`. The current way to do this would be to initialize the State by calling 
```kt
rememberZoomableState { zoomChange, offsetChange, rotationChange ->
    scale *= zoomChange
    offset += offsetChange
}
```

I think an overload of rememberTransformableState which takes three boolean Values to disable all three actions would be a good idea.

I might also implement a toggle for the EasyZoomableImage. Would you prefer different toggles for lockRotationZoomPan and general Rotation on/off or an Enum class with `OFF`, `ALWAYS` and `LOCK_ROTATION_ON_ZOOM_PAN`

**Comment by ajans** [comment]
Thank you for your engagement!

I think an Enum would be more expressive and thus less confusing.

Since I use the `GlideImage`-composable from the landscapist-lib as content for the `Zoomable`, I have no opinion about `EasyZoomableImage`.

**Comment by Mr-Pine** [comment]
This should be possible in v1.1.0 by initializing the ZoomableState with
 `rememberZoomableState(rotationBehavior = ZoomableState.Rotation.DISABLED)`

**Comment by ajans** [comment]
Thank you for the speedy reaction, I will try it right now and give you feedback.
